# Generated by Django 4.2.7 on 2023-11-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workandservis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workservis',
            name='kind',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'Draft'), ('ARCHIVE', 'Archive')], default='DRAFT', max_length=10),
        ),
    ]
